### ISSUE TITLE
Camera parameters and depth map

### ISSUE THREAD

**Issue by spacelu** [NagabhushanSN95/Pose-Warping#4]
Hi, thanks for the work. I am new to this field and tried to run this on some RGBD datasets. I am confused about the camera parameters and their relation to the depth. Is the transformation matrix used in the code a camera_to_world matrix or a world_to_camera matrix? And as mentioned in #3, the unit of depth map is supposed to be the same as the unit of translation vector. However, I am wondering if it matters what world coordinate convention is used to define the translation vector. 
Thanks in advance!

**Comment by NagabhushanSN95** [comment]
The transformation matrices are in world to camera format.

**Comment by spacelu** [comment]
Thanks for the information. It works for my project.
