### ISSUE TITLE
i wonder where this paper "Pose Warping for View Synthesis"could be found?

### ISSUE THREAD

**Issue by lvZic** [NagabhushanSN95/Pose-Warping#5]

**Comment by NagabhushanSN95** [comment]
Hi,

There is no accompanying paper for this work. However, we have used this in our work [Revealing Disocclusions in Temporal View Synthesis through Infilling Vector Prediction](https://nagabhushansn95.github.io/publications/2021/ivp.html). You can check Section B.1 in the supplement of this paper for more details.
