### ISSUE TITLE
depth file

### ISSUE THREAD

**Issue by DejavuPy7** [NagabhushanSN95/Pose-Warping#6]
Hi, I've tried the script on the data you provided and it works fine. But when I use a depth inferenced by MiDas the result went wrong. How did you get depth1.npy? By some depth sensor or algorithm? Thanks a lot.

**Comment by chenkangjie1123** [comment]
I also found that the scale of the depth value obtained by the midas model greatly affects the warp result. I also want to know how to standardize the scale of the depth value.

**Comment by NagabhushanSN95** [comment]
Yes, the scale is very important in depth-based-warping. The sample image I have provided is rendered by Blender. You can find more details and the full database [here](https://nagabhushansn95.github.io/publications/2021/ivp.html#database).

MiDas, as I understand it, is a mono-depth model i.e. it generates depth from a single image. This is an under-constrained problem and the depths from MiDas can never be fully trusted for the purpose of depth-based-warping. There can be so many scenarios where the image looks the same but the depth could be different.

The best source of depth is from a sensor or depth estimated from a multi-view stereo model such as [DPS-net](https://github.com/sunghoonim/DPSNet). Note that the scale/units of the depth should be the same as that of the translation vector in the camera extrinsics (4th column - if indexing starts at 1).
